// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqbhFThKMhUCyIUuMp1UvrIK9SK-ziBkY',
    appId: '1:799156312283:web:6df5c8fba7c720379d54fe',
    messagingSenderId: '799156312283',
    projectId: 'my-flutter-app-20-8',
    authDomain: 'my-flutter-app-20-8.firebaseapp.com',
    storageBucket: 'my-flutter-app-20-8.appspot.com',
    measurementId: 'G-MR3B4ZQS0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUot5u3uZCZFeHz6cL56RHlDxg0gdawsA',
    appId: '1:799156312283:android:92cac84b820b86349d54fe',
    messagingSenderId: '799156312283',
    projectId: 'my-flutter-app-20-8',
    storageBucket: 'my-flutter-app-20-8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn8HnXbdaJQij5dleokNZu762CqSynBxk',
    appId: '1:799156312283:ios:7a048cc10d2bf1d89d54fe',
    messagingSenderId: '799156312283',
    projectId: 'my-flutter-app-20-8',
    storageBucket: 'my-flutter-app-20-8.appspot.com',
    iosClientId: '799156312283-38jmjuh1gaongs76pt5q83iqei909kas.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMobile2008',
  );
}
